### ISSUE TITLE
Sorting on Name goes by Artist first

### ISSUE THREAD

**Issue by dmazurek** [jpgilchrist/gpscy-karaoke#3]
If you sort by Name, it sorts by name within each artist, not over all the names.

**Comment by jermahs** [comment]
@dmazurek yeah I didn't create a way to "clear" the sort for the columns. So, a sort on both columns is always applied. Do you want to be able to clear the sort?

**Comment by dmazurek** [comment]
Ah, yes. So it should only sort on one column ever -- that's how we had the
books. One was sorted by artist, the other by title.

**Comment by jermahs** [comment]
Okay. That works.

**Comment by dmazurek** [comment]
#6 fixes this

**Comment by dmazurek** [comment]
Just realized it should still sort by both columns, but make the clicked column primary. I.e. if you click Artist, sort by artist, then title. If you click Title, sort by title, then artist.

It did that already for artist, just not for title.
