### ISSUE TITLE
Fix CSS for Header Input Filters

### ISSUE THREAD

**Issue by jermahs** [jpgilchrist/gpscy-karaoke#8]
![image](https://user-images.githubusercontent.com/5065660/31388079-d9448030-ad9a-11e7-81e8-c88cc66f7ed3.png)

**Comment by dmazurek** [comment]
Yuck, I know. I don't know what to do here... the spacing is normal on some browsers and busted on others. :-/

I saw some code that calculates the exact width of the scrollbar. I think that's the only way to really fix this across all browsers.

http://jdsharp.us/jQuery/minute/calculate-scrollbar-width.php

**Comment by dmazurek** [comment]
When you filter down to just a few entries and the scrollbar disappears, the alignment breaks again.

![alignment-no-scrollbar](https://user-images.githubusercontent.com/1128804/31472527-482488c4-aebd-11e7-9839-0b04b1f507d2.png)
